# Generated by Django 3.0.8 on 2020-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='상품이름')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('photo', models.ImageField(upload_to='', verbose_name='상품사')),
                ('want', models.CharField(max_length=32, verbose_name='원하는물건')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'db_table': 'baton_Product',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts',
        ),
    ]
